[connections.my_database]
type = "sql"
dialect = "postgresql"
username = "user"
password = "password"
host = "localhost"     # Use localhost or the Docker service name
port = 5432            # Port number for PostgreSQL
database = "mydb"      # Database name
